"""
Builds ceo_dashboard/notebooks/ceo_dashboard.ipynb programmatically with
nbformat, one stage at a time. Re-run after editing a STAGE_N_CELLS list to
regenerate the notebook. Keeping notebook construction in a script (rather
than hand-editing JSON) makes each stage's cells reviewable as a diff.
"""
import nbformat as nbf

NB_PATH = "ceo_dashboard/notebooks/ceo_dashboard.ipynb"


def md(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(src)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


# ===========================================================================
# STAGE 1 -- Data generator + swappable loader
# ===========================================================================
STAGE_1_CELLS = [
    md(
"""# CEO Cost & Margin Dashboard — D2C Fashion

**⚠️ ALL DATA IN THIS NOTEBOOK IS SYNTHETIC.** It is generated by a seeded
random data generator to look like a plausible small D2C fashion brand. It
is not real sales, marketing, or inventory data, and no business conclusion
should be drawn from the specific numbers — only from the *methodology*.

## What this notebook is

A two-layer analytics engine for a goods-selling business's cost and margin
performance, built so a CEO can see revenue, margin, working capital,
returns, acquisition efficiency, and inventory health in one place — with
every number traceable to a plain-language formula.

**Layer 1 — Universal Core**: KPIs that apply to *any* goods business
(revenue, gross margin, contribution margin, COGS/opex breakdown,
inventory turns, working-capital cycle, SKU concentration).

**Layer 2 — Fashion Module**: KPIs specific to D2C fashion (returns rate,
CAC/ROAS/MER, LTV:CAC, AOV, repeat rate, cohort retention, sell-through,
weeks-of-cover, markdown/dead-stock %), defined against the **same** core
engine via a config file rather than by editing the engine itself. Swapping
industries (e.g. to FMCG or auto parts) is meant to mean *writing a new
config*, not touching Layer 1's calculation code.

## No black boxes

Every KPI's formula and the business question it answers is written out in
a markdown cell before it's used. If a line of code in this notebook can't
be explained in plain language in an interview, it doesn't belong here.

## Build stages (this notebook is built incrementally)

1. **Data generator + swappable loader** ← this notebook, current stage
2. Cleaning + Universal Core KPIs
3. Fashion industry module (returns, CAC, cohorts, sell-through)
4. Dashboard / visualizations
5. Margin-risk alert model
6. Demand / inventory forecast model

---
## Stage 1 — Synthetic data generator and the swappable column-mapping loader

**Goal of this stage:** produce a realistic order-level D2C fashion dataset
and prove that swapping in a real CSV later requires editing only a
column-mapping dictionary — never the analysis code."""
    ),
    md("### Setup — installs (Colab) and imports"),
    code(
"""# Colab: uncomment the line below on first run in a fresh Colab environment.
# !pip install -q pandas numpy matplotlib plotly scikit-learn

import sys
sys.path.append("..")  # so `from src import ...` resolves when running from notebooks/

import pandas as pd
import numpy as np

from src import schema
from src import data_generator as dg
from src import data_loader as dl

pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 140)"""
    ),
    md(
"""### Why three tables, not one giant spreadsheet

A real D2C business's data doesn't naturally live in a single flat table,
and forcing it into one would hide real structure:

| Table | Grain | Why it's separate |
|---|---|---|
| `orders` | one row per **order line item** | The core fact table: revenue, cost, returns, and customer identity all live here. |
| `marketing_spend` | one row per **(month, channel)** | Ad spend is a channel-level input (an ad platform invoice) — it isn't a property of one order, so attaching a "spend" column to every order line would double- or triple-count it the moment an order has multiple line items. |
| `inventory_snapshots` | one row per **(month, SKU)** | Turns, days-of-inventory, and sell-through all need what *wasn't* sold (opening/closing stock), which the orders table alone can never tell you. |

This mirrors how the data actually arrives from a real stack (Shopify/POS
export, ad-platform report, WMS export) — three separate files that get
joined for analysis, not reconciled from a single source."""
    ),
    md(
"""### Generating the synthetic dataset

`src/data_generator.py` builds all three tables from a single seeded
`numpy.random.Generator` (default seed 42), so the dataset is 100%
reproducible — rerunning this cell (or the whole notebook) on any machine
produces byte-identical output.

Key generation choices, made explicit here so nothing downstream is a
surprise:
- **12 months** of order-line data (Jul 2025 – Jun 2026), 6 product
  categories, ~150 SKUs, an order-volume ramp (the brand is growing) and two
  seasonal sale-driven demand spikes.
- **Return rates are category-specific and deliberately high for
  fit-sensitive categories** (Dresses ~38%, Tops ~32%, Bottoms ~28%),
  landing in the 20–40% range real fashion brands see, specifically so the
  margin impact of returns is visible rather than a rounding error.
- **Customers arrive over time and a share of them re-order** later in the
  year, which is what makes repeat-purchase-rate and cohort retention
  (Stage 3) meaningful rather than trivially zero.
- **Marketing spend per channel roughly tracks the orders that channel is
  credited with**, plus noise and a channel-specific efficiency factor —
  so CAC/ROAS differ meaningfully by channel instead of being flat by
  construction.
- **Inventory purchasing is deliberately imperfect for a subset of SKUs**
  (some over-bought, some under-bought) so later stages have genuine
  overstock/stockout cases to detect.

Full assumptions are documented in the `data_generator.py` module
docstring."""
    ),
    code(
"""data = dg.generate_all(seed=42)
orders_df = data["orders"]
marketing_df = data["marketing_spend"]
inventory_df = data["inventory_snapshots"]

print("SYNTHETIC DATA — generated with seed=42, fully reproducible\\n")
for name, df in data.items():
    print(f"{name:22s} shape={df.shape}")"""
    ),
    md("### Orders table — schema and sample"),
    code(
"""print("orders.csv column dtypes:\\n")
print(orders_df.dtypes)
orders_df.head(5)"""
    ),
    md(
"""**Column-by-column explanation of `orders`** (one row = one order line item):

| Column | Meaning |
|---|---|
| `order_id` | Groups line items placed in the same checkout — an order with 2 SKUs is 2 rows sharing this value. |
| `order_line_id` | Unique key for this row (`order_id` + line number). |
| `order_date` | Date the order was placed. |
| `customer_id` | Identifies the buyer; the same value recurs across a customer's repeat orders — this is what makes repeat-rate and cohort analysis possible. |
| `sku_id` | Product+variant identifier (e.g. `DRE-014`). |
| `category` | Product category — Tops, Bottoms, Dresses, Outerwear, Footwear, or Accessories. |
| `size` | Size variant of the SKU. |
| `quantity` | Units on this line (mostly 1, occasionally 2). |
| `unit_price` | Realized selling price per unit, **after** any discount — this is what actually hit revenue, not the list price. |
| `unit_cogs` | Cost of goods per unit for this SKU (manufacturing/sourcing cost). |
| `shipping_cost` | Fulfillment/shipping cost allocated to this line. |
| `payment_gateway_fee` | Payment processor fee allocated to this line (~2.1% + a small fixed fee, typical of Indian payment gateways). |
| `marketing_channel` | The channel credited with driving the *parent order* (Instagram Ads, Google Ads, Influencer, Affiliate, or Organic/Email). |
| `is_return` | `True` if this specific line item was returned. |
| `return_date` | Date of the return; `NaT` (missing) if never returned. |"""
    ),
    md("### Marketing spend table — schema and sample"),
    code(
"""print("marketing_spend.csv column dtypes:\\n")
print(marketing_df.dtypes)
marketing_df.head(5)"""
    ),
    md(
"""**Column-by-column explanation of `marketing_spend`** (one row = one
channel's total spend in one month):

| Column | Meaning |
|---|---|
| `month` | Calendar month, `YYYY-MM`. |
| `channel` | Marketing channel (matches `orders.marketing_channel`). |
| `spend` | Total spend on that channel that month. `Organic/Email` is always 0 — it represents word-of-mouth, direct, and retention email, not a paid acquisition channel. |

This table is joined to `orders` (aggregated by month + channel) when
computing CAC/ROAS in Stage 3 — it is never merged row-for-row onto order
lines, because that would silently duplicate spend across every line item
of a multi-item order."""
    ),
    md("### Inventory snapshots table — schema and sample"),
    code(
"""print("inventory_snapshots.csv column dtypes:\\n")
print(inventory_df.dtypes)
inventory_df.head(5)"""
    ),
    md(
"""**Column-by-column explanation of `inventory_snapshots`** (one row = one
SKU's stock position in one month):

| Column | Meaning |
|---|---|
| `sku_id` | Matches `orders.sku_id`. |
| `month` | Calendar month, `YYYY-MM`. |
| `beginning_inventory` | Units on hand at the start of the month. |
| `units_received` | Units restocked during the month. |
| `units_sold` | Units sold during the month (gross, before returns) — reconciles with `orders` grouped by SKU and month. |
| `ending_inventory` | `beginning_inventory + units_received - units_sold`, floored at 0. Next month's `beginning_inventory` always equals this value — verified in the test suite. |"""
    ),
    md("### Quick sanity check: does this data look like a real fashion brand?"),
    code(
"""total_revenue = (orders_df["unit_price"] * orders_df["quantity"]).sum()
print(f"Date range        : {orders_df['order_date'].min().date()} to {orders_df['order_date'].max().date()}")
print(f"Unique orders      : {orders_df['order_id'].nunique():,}")
print(f"Unique customers   : {orders_df['customer_id'].nunique():,}")
print(f"Unique SKUs        : {orders_df['sku_id'].nunique()}")
print(f"Order line items   : {len(orders_df):,}")
print(f"Gross revenue (pre-return, INR): {total_revenue:,.0f}")
print()
print("Return rate by category (target: fit-sensitive categories land in the realistic 20-40% fashion range):")
print(orders_df.groupby("category")["is_return"].mean().sort_values(ascending=False).round(3))"""
    ),
    md(
"""Dresses, Tops, and Bottoms — the fit-sensitive categories — land in the
28–38% return-rate range, Accessories sits under 10%. This spread is by
design (see the generator's category return-rate table) and is what will
make the returns-driven margin impact visible in Stage 3, rather than a
number too small to matter."""
    ),
    md("### The swappable loader — proving a real CSV export could replace this data with zero analysis-code changes"),
    code(
"""import os

# Save the generated tables exactly as a real export would arrive: plain CSVs.
os.makedirs("../data/synthetic", exist_ok=True)
dg.save_all(data, "../data/synthetic")
print("Saved:", os.listdir("../data/synthetic"))"""
    ),
    md(
"""`src/data_loader.py` reads these CSVs and renames columns using a mapping
dict (`schema.DEFAULT_ORDERS_MAPPING`, etc.) — by default an identity
mapping, since the synthetic data already uses canonical column names. To
prove this is a real swap point (not just a pass-through), the cell below
simulates a real export with **different column headers** — `"Order No"`
instead of `order_id`, `"Selling Price"` instead of `unit_price` — and
loads it by editing only a mapping dict, changing no code in
`data_loader.py` or any calculation module."""
    ),
    code(
"""# Simulate a real export with different headers than our canonical schema.
fake_export = pd.read_csv("../data/synthetic/orders.csv")
fake_export = fake_export.rename(columns={"order_id": "Order No", "unit_price": "Selling Price"})
fake_export.to_csv("../data/synthetic/_demo_real_export.csv", index=False)

# Build a custom mapping: copy the default, then repoint the two changed headers.
custom_mapping = dict(schema.DEFAULT_ORDERS_MAPPING)
del custom_mapping["order_id"]
del custom_mapping["unit_price"]
custom_mapping["Order No"] = schema.ORDER_ID
custom_mapping["Selling Price"] = schema.UNIT_PRICE

swapped_df = dl.load_orders("../data/synthetic/_demo_real_export.csv", mapping=custom_mapping)
print("Loaded a differently-headed file using only a mapping-dict edit.")
print("Resulting columns match the canonical schema:", list(swapped_df.columns) == schema.ORDERS_SCHEMA)
swapped_df.head(3)"""
    ),
    code(
"""os.remove("../data/synthetic/_demo_real_export.csv")  # clean up the demo file"""
    ),
    md(
"""If a real export is missing a column the engine needs, the loader raises
immediately with the missing column's name (`schema.validate_columns`),
rather than letting a KPI compute silently on absent data. This is checked
in `tests/test_stage1_data.py::test_loader_raises_on_missing_column`."""
    ),
    md(
"""---
## Stage 1 summary

Built a fully synthetic, seeded, reproducible 12-month D2C fashion dataset
across three tables — `orders` (order-line grain, 25,930 lines / ~18,600
orders / 12,002 customers / 150 SKUs), `marketing_spend` (channel × month),
and `inventory_snapshots` (SKU × month) — with category-specific return
rates realistically landing in the 20–40% fashion range (Dresses ~38%,
Tops ~32%) so their margin impact will be visible later. Every column is
documented above. The data-loading layer (`src/data_loader.py` +
`src/schema.py`) was proven swappable: a differently-headed CSV loads
correctly by editing only a column-mapping dictionary, with no changes to
loader or analysis code, and a missing required column fails loudly instead
of silently. 9 automated tests cover schema shape, reproducibility,
inventory-chain consistency, and the loader swap/failure paths (all
passing).

**Stopping here for review before Stage 2 (cleaning + Universal Core KPIs).**"""
    ),
]


# ===========================================================================
# STAGE 2 -- Cleaning + Universal Core KPIs
# ===========================================================================
STAGE_2_CELLS = [
    md(
"""---
## Stage 2 — Cleaning + Universal Core KPIs (Layer 1)

Two things happen in this stage:

1. **Cleaning** (`src/clean.py`): a small, logged pipeline that would catch
   the mess a real raw export has (duplicates, missing costs, inconsistent
   text, invalid values) -- demonstrated against a deliberately messy
   sample, then run for real against the canonical dataset.
2. **Universal Core KPIs** (`src/core.py`): revenue, margin, cost
   breakdowns, inventory efficiency, and working capital -- every formula
   works for *any* goods business. Nothing fashion-specific appears in
   `core.py`; that boundary is enforced by construction, not just by
   convention."""
    ),
    md(
"""### Pre-flight diagnostic (before writing any KPI code)

Before building the core layer, two questions needed real numbers, not
assumptions:

1. **Does this dataset actually contain loss-making SKUs and channels?** A
   margin-risk alert model (Stage 5) is pointless to build against data
   where nothing is ever unprofitable.
2. **How is marketing spend currently related to CAC?** Is it already
   *true* CAC (spend ÷ newly acquired customers), or just a cost-per-order
   figure? This matters because Stage 3/5 will build real CAC on top of
   this data, and the difference changes every number downstream.

This diagnostic uses one-off code, not `core.py` functions -- CAC and
marketing-loaded margin are Layer 2 (fashion/channel) concepts and
deliberately do not belong in the universal core engine. The proper,
reusable versions get built in Stage 3."""
    ),
    code(
"""import pandas as pd
import numpy as np

from src import data_generator as dg
from src import clean
from src import core
from src import schema

data = dg.generate_all(seed=42)
cleaned_preview, _ = clean.clean_orders(data["orders"])
econ_preview = core.add_line_economics(cleaned_preview)
marketing_df = data["marketing_spend"]

# ---- Q1: cost-per-order vs true CAC (spend / newly acquired customers) ----
orders_only = econ_preview.drop_duplicates(subset=schema.ORDER_ID).copy()
first_orders = (orders_only.sort_values(schema.ORDER_DATE)
                 .drop_duplicates(subset=schema.CUSTOMER_ID, keep="first"))

orders_by_channel = orders_only.groupby(schema.MARKETING_CHANNEL).size()
new_cust_by_channel = first_orders.groupby(schema.MARKETING_CHANNEL).size()
spend_by_channel = marketing_df.groupby(schema.SPEND_CHANNEL)[schema.SPEND_AMOUNT].sum()

cac_check = pd.DataFrame({
    "total_spend": spend_by_channel,
    "total_orders_credited": orders_by_channel,
    "total_new_customers": new_cust_by_channel,
}).fillna(0)
cac_check["cost_per_order"] = cac_check["total_spend"] / cac_check["total_orders_credited"]
cac_check["true_cac_per_new_customer"] = (
    cac_check["total_spend"].replace(0, np.nan) / cac_check["total_new_customers"].replace(0, np.nan)
)
print("Q1 -- cost-per-order vs true CAC by channel:")
print(cac_check.round(2).to_string())
print()
print("The generator builds marketing_spend as (a per-order cost rate) x (ALL orders credited to")
print("the channel, new + repeat). So spend / orders_credited recovers a COST-PER-ORDER, not true")
print("CAC. True CAC (spend / new customers only) is 20-30% higher for every paid channel, since")
print("spend also covers repeat-customer orders attributed to that channel, which the new-customer")
print("count excludes. Stage 3's CAC KPI will use the TRUE definition (spend / new customers).")"""
    ),
    code(
"""# ---- Q2: how many SKUs / channels are loss-making after returns + CAC? ----

# Channel-level: contribution margin generated by orders attributed to a
# channel vs. total spend on that channel (a channel "mini P&L").
cm_by_channel = econ_preview.groupby(schema.MARKETING_CHANNEL)["contribution_margin_line"].sum()
channel_pnl = pd.DataFrame({
    "contribution_margin": cm_by_channel,
    "orders": orders_by_channel,
    "spend": spend_by_channel,
}).fillna(0)
channel_pnl["cac_cost_per_order"] = channel_pnl["spend"] / channel_pnl["orders"]
channel_pnl["cm_after_cac"] = channel_pnl["contribution_margin"] - channel_pnl["spend"]
n_neg_channels = int((channel_pnl["cm_after_cac"] < 0).sum())

print("Q2a -- channel P&L (contribution margin generated minus spend on that channel):")
print(channel_pnl.round(2).to_string())
print(f"\\nChannels with NEGATIVE contribution margin after CAC: {n_neg_channels} of {len(channel_pnl)}")

# SKU-level: allocate each channel's per-order spend pro-rata across that
# order's lines by revenue share, down to SKU grain.
order_net_rev = econ_preview.groupby(schema.ORDER_ID)["net_revenue_line"].transform("sum")
line_count = econ_preview.groupby(schema.ORDER_ID)[schema.ORDER_ID].transform("count")
econ_preview["line_share"] = np.where(order_net_rev > 0, econ_preview["net_revenue_line"] / order_net_rev, 1 / line_count)
econ_preview["allocated_cac"] = (
    econ_preview[schema.MARKETING_CHANNEL].map(channel_pnl["cac_cost_per_order"]) * econ_preview["line_share"]
)
econ_preview["cm_after_cac_line"] = econ_preview["contribution_margin_line"] - econ_preview["allocated_cac"]

sku_cac = econ_preview.groupby(schema.SKU_ID).agg(
    contribution_margin=("contribution_margin_line", "sum"),
    cm_after_cac=("cm_after_cac_line", "sum"),
).reset_index()
n_neg_sku_before_cac = int((sku_cac["contribution_margin"] < 0).sum())
n_neg_sku_after_cac = int((sku_cac["cm_after_cac"] < 0).sum())

print()
print(f"Q2b -- SKUs with negative contribution margin BEFORE CAC (returns already netted in): {n_neg_sku_before_cac} of {len(sku_cac)}")
print(f"Q2b -- SKUs with negative contribution margin AFTER pro-rata CAC allocation: {n_neg_sku_after_cac} of {len(sku_cac)}")
print()
print("Bottom 6 SKUs by contribution margin after CAC:")
print(sku_cac.sort_values("cm_after_cac").head(6).round(2).to_string(index=False))"""
    ),
    md(
"""**Findings, stated plainly:**

- **0 of 5 channels** show negative contribution margin after CAC. Even
  Influencer, the least efficient paid channel, still clears its own
  acquisition cost by a wide margin (contribution margin per order ≈ ₹1,093
  vs. CAC-implied cost per order ≈ ₹500).
- **0 of 150 SKUs** are loss-making before CAC (returns already netted
  in); only **3 of 150** turn negative after a pro-rata CAC allocation, and
  a handful more sit within a few hundred rupees of zero.
- **Flagging this explicitly, as requested**: this signal is too thin. A
  margin-risk alert model (Stage 5) trained or ruled against data where
  almost nothing is ever unprofitable will have nothing real to catch. The
  category economics (60%+ gross margin everywhere) and channel CAC
  (modest relative to a ~₹1,900 AOV) are healthy by construction, with no
  deliberately weak SKUs or channels seeded in Stage 1.
- **This is a data-generation calibration issue, not a Stage 2 problem.**
  Universal Core KPIs (below) are correct regardless of how many things
  are profitable. The fix -- seeding a small number of genuinely
  loss-making SKUs (e.g. high-return, thin-margin items) and one
  under-performing channel -- belongs in `src/data_generator.py`, and is
  deferred to just before Stage 5 rather than reopening the already-
  reviewed Stage 1 dataset here without cause."""
    ),
    md(
"""### Cleaning pipeline

`src/clean.py` runs four named steps, each logging what it found and what
policy it applied -- nothing is silently imputed or silently dropped:

| Step | What it catches | Policy |
|---|---|---|
| `normalise_categories` | inconsistent casing/whitespace (e.g. `"TOPS  "`) | strip + title-case |
| `deduplicate_order_lines` | exact duplicate `order_line_id` (e.g. a webhook retry) | drop, keep first |
| `flag_missing_cogs` | null `unit_cogs` | **never imputed** -- row kept, flagged `valid_economics=False`, excluded from every cost/margin KPI |
| `flag_invalid_economics` | `quantity<=0` or `unit_price<=0` (a data bug, not a real sale) | **never coerced** -- same flag/exclude policy |

To prove this pipeline does real work (the canonical Stage 1 dataset is
clean by construction), the next cell runs it against a deliberately
messy copy first -- `src/raw_noise.py` injects duplicate rows, missing
costs, casing issues, and invalid values at realistic small rates,
simulating what a real raw export actually looks like."""
    ),
    code(
"""from src import raw_noise

rng = np.random.default_rng(123)
messy_orders = raw_noise.make_messy(data["orders"], rng)
print(f"Messy sample: {len(messy_orders):,} rows (vs {len(data['orders']):,} clean rows -- duplicates added)")

cleaned_messy, decision_log = clean.clean_orders(messy_orders)
print("\\nDecision log (cleaning the messy sample):")
print(decision_log.to_string(index=False))
print(f"\\nRows flagged valid_economics=False: {(~cleaned_messy['valid_economics']).sum()} of {len(cleaned_messy)}")"""
    ),
    md(
"""Now the real thing: cleaning the actual canonical dataset. Because it was
generated clean, every step should report **zero** rows affected -- which
is itself worth confirming, not assuming."""
    ),
    code(
"""orders_clean, decision_log_real = clean.clean_orders(data["orders"])
print("Decision log (cleaning the real canonical orders table):")
print(decision_log_real.to_string(index=False))
assert (decision_log_real["rows_affected"] == 0).all(), "canonical data should be clean by construction"
print("\\nConfirmed: canonical data is clean by construction, as expected.")
print(f"orders_clean shape: {orders_clean.shape} (includes new 'valid_economics' column)")

opex_df = data["opex"]
inventory_df = data["inventory_snapshots"]"""
    ),
    md(
"""From here on, **`orders_clean`** (the output of `clean.clean_orders`) is
the input every Universal Core function expects. Every function below
calls `core.add_line_economics` first internally, which both filters to
`valid_economics == True` rows and derives the per-line revenue/cost
columns every KPI is built from -- see its docstring in `src/core.py` for
the exact return-handling model (returns zero out revenue and COGS, but
NOT shipping/payment fees, which is what makes returns a real margin
drag)."""
    ),
    md(
"""### KPI 1 — Revenue trend

**Formula:** `gross_revenue` = Σ(unit_price × quantity) over all lines;
`net_revenue` = the same, excluding returned lines; `returned_revenue` =
gross − net.
**CEO question:** is the top line growing, and how much of it is being
given back through returns each month?"""
    ),
    code(
"""revenue_trend = core.revenue_trend(orders_clean)
revenue_trend"""
    ),
    md(
"""### KPI 2 — Gross Margin

**Formula:** Gross Margin % = (Net Revenue − Net COGS) / Net Revenue.
**CEO question:** is the core product economics (price vs. cost to
make/source it) healthy, independent of fulfillment, marketing, or
overhead cost?"""
    ),
    code(
"""gross_margin_trend = core.gross_margin_trend(orders_clean)
gross_margin_trend"""
    ),
    md(
"""### KPI 3 — Contribution Margin (absolute and per order)

**Formula:** Contribution Margin = Net Revenue − Net COGS − Variable
Fulfillment Costs (shipping + payment gateway fees). Contribution Margin
per Order = Contribution Margin ÷ number of distinct orders that month.
**CEO question:** after making/sourcing the product AND fulfilling the
order, how much is left to cover marketing and overhead -- per rupee of
revenue and per order taken? (Marketing-loaded economics is a Layer 2
concern, built on top of this in Stage 3/5.)

Returns are already netted into Net Revenue/Net COGS above, but that
hides exactly how much margin they cost. The bridge below makes it a
visible, separate line."""
    ),
    code(
"""contribution_margin_trend = core.contribution_margin_trend(orders_clean)
contribution_margin_trend"""
    ),
    code(
"""returns_bridge = core.returns_margin_bridge(orders_clean)
print("Returns margin bridge (gross_contribution_margin = as if nothing were ever returned):")
print(returns_bridge.round(0).to_string(index=False))

total_impact = returns_bridge["returns_margin_impact"].sum()
total_gross_cm = returns_bridge["gross_contribution_margin"].sum()
print(f"\\nOver 12 months, returns cost ₹{-total_impact:,.0f} of contribution margin")
print(f"-- {-total_impact/total_gross_cm:.1%} of what contribution margin would have been with no returns at all.")"""
    ),
    md(
"""**Returns wipe out roughly 29% of gross contribution margin over the
year** -- this is the single clearest argument in the whole dashboard for
treating returns as a first-class margin driver, not a customer-service
footnote. Stage 3 breaks this down by category and SKU."""
    ),
    md(
"""### KPI 4 — COGS breakdown and Operating Expense breakdown

**Formula (COGS):** Σ(net_cogs_line) grouped by category, as a % of total
COGS. **CEO question:** where is cost of goods actually concentrated?

**Formula (Opex):** Σ(amount) grouped by expense_category, as a % of
total opex. **CEO question:** where does the fixed overhead that isn't
tied to any single order actually go?

(`opex.csv` is a Stage-2 addition to the dataset -- Layer 1's "operating
expense breakdown" KPI needs overhead data that no order-level row can
ever contain, since rent/salaries/tools aren't a property of any one
order. See `src/data_generator.py::generate_opex`.)"""
    ),
    code(
"""cogs_breakdown = core.cogs_breakdown(orders_clean)
print("COGS breakdown by category:")
print(cogs_breakdown.round(3).to_string(index=False))

print()
opex_breakdown = core.opex_breakdown(opex_df)
print("Operating expense breakdown by category:")
print(opex_breakdown.round(3).to_string(index=False))"""
    ),
    md(
"""### KPI 5 — The monthly P&L: Operating Profit

**Formula:** Operating Profit = Contribution Margin − Operating Expenses.
Operating Margin % = Operating Profit / Net Revenue.
**CEO question:** after covering product, fulfillment, AND fixed
overhead, is the business actually profitable month to month? (This is
still "profit before marketing" -- marketing-loaded profitability is a
Stage 3/5 concern -- documented here so that's not mistaken for the full
picture.)"""
    ),
    code(
"""pnl_trend = core.company_pnl_trend(orders_clean, opex_df)
money_cols = ["contribution_margin_abs", "total_opex", "operating_profit", "net_revenue"]
pnl_display = pnl_trend.copy()
pnl_display[money_cols] = pnl_display[money_cols].round(0)
pnl_display["operating_margin_pct_display"] = (pnl_display["operating_margin_pct"] * 100).round(1)
pnl_display.drop(columns=["operating_margin_pct"])"""
    ),
    md(
"""### KPI 6 — Margin by SKU and SKU concentration

**Formula (margin by SKU):** for each SKU: net_revenue, net_cogs,
gross_margin_abs/pct, contribution_margin_abs, units_sold (net of
returns), contribution_margin_per_unit.
**CEO question:** which specific products actually make money, and which
sell but quietly lose money once fulfillment cost is counted? This table
feeds Stage 5's alerts directly.

**Formula (concentration):** rank SKUs by net_revenue descending;
cumulative_share = running total ÷ total net revenue. Reports the revenue
share held by the top 5/10/20 SKUs and by the top 20% of SKUs by count.
**CEO question:** how dependent is the business on a small number of hero
products? High concentration means one SKU going out of stock or falling
out of fashion is a real revenue risk."""
    ),
    code(
"""margin_by_sku = core.margin_by_sku(orders_clean)
print("Top 10 SKUs by contribution margin:")
margin_by_sku.sort_values("contribution_margin_abs", ascending=False).head(10)"""
    ),
    code(
"""sku_ranked, concentration_summary = core.sku_concentration(orders_clean)
print("SKU revenue concentration summary:")
for k, v in concentration_summary.items():
    print(f"  {k}: {v:.1%}" if isinstance(v, float) else f"  {k}: {v}")
print()
print("Top 10 SKUs by revenue (ranked, with cumulative share):")
sku_ranked[["sku_id", "category", "net_revenue", "revenue_share", "cumulative_share"]].head(10)"""
    ),
    md(
"""The top 10 SKUs (of 150) generate about 18% of revenue, and the top 20%
of SKUs (30 products) generate about 42% -- concentrated, but not
dangerously so; no single hero product the business is dependent on."""
    ),
    md(
"""### KPI 7 — Inventory turns and Days of Inventory Outstanding (DIO)

**Formula:** Inventory Turns (monthly) = COGS of units sold that month ÷
Average Inventory Value that month, where Average Inventory Value =
(beginning + ending inventory) / 2, valued at each SKU's unit COGS.
Annualized Turns = monthly turns × 12. **DIO = 365 ÷ Annualized Turns.**
**CEO question:** how many times a year is inventory capital being sold
through (higher = capital working harder), and on average how many days
of stock sit in the warehouse before selling (higher DIO = cash trapped
in slow-moving inventory)?"""
    ),
    code(
"""inventory_turns = core.inventory_turns(inventory_df, orders_clean)
inventory_turns.round(2)"""
    ),
    md(
"""### KPI 8 — Working-capital cycle (DSO, DPO, DIO, CCC)

**⚠️ Explicit assumption, not derived from data:** this dataset has no
accounts-receivable or accounts-payable sub-ledger, so **DSO and DPO are
NOT computed from data** -- they are stated business assumptions:

- **DSO (Days Sales Outstanding) = 2 days**, assumed. A D2C brand collects
  payment upfront at checkout via a payment gateway -- there is no
  customer credit period. The 2 days represents a typical payment
  gateway settlement lag (money in hand to money in the bank), not
  customer credit terms.
- **DPO (Days Payable Outstanding) = 30 days**, assumed. Represents a
  typical negotiated net-30 supplier payment term in fashion sourcing.
  There is no payables ledger in this dataset to derive it from.
- **DIO is genuinely derived** from the inventory data above -- it's the
  one real, measured input to this formula.

**Formula:** Cash Conversion Cycle (CCC) = DSO + DIO − DPO.
**CEO question:** how many days of the business's own cash are tied up
funding one cycle of buying, holding, and selling inventory, net of how
long it can delay paying suppliers? Lower (or negative) CCC means the
business needs less of its own capital to fund growth."""
    ),
    code(
"""working_capital = core.working_capital_cycle(inventory_df, orders_clean)
working_capital.round(1)"""
    ),
    md(
"""---
## Stage 2 summary

Built the cleaning pipeline (`src/clean.py`) and the full Universal Core
KPI engine (`src/core.py`), both dependent on nothing fashion-specific.
The **pre-flight diagnostic**, run before writing any KPI code, surfaced a
real gap: **0 of 5 marketing channels and only 3 of 150 SKUs show negative
contribution margin even after CAC is allocated** -- too thin a signal for
Stage 5's alert model, and flagged explicitly rather than quietly
built around. Cleaning was proven to catch real issues (duplicate rows,
missing costs, casing, invalid values) against an injected-messiness
sample, then run for real against the canonical data, which -- as
expected, since it's generated clean -- logged zero rows affected on
every step. Eight Universal Core KPIs were computed with real output:
revenue trend, gross margin, contribution margin (plus a returns-margin
bridge showing returns cost **29% of gross contribution margin** over the
year), COGS/opex breakdown, a monthly operating-profit P&L, margin-by-SKU
with revenue concentration (top 10 SKUs = 18% of revenue), inventory
turns/DIO, and the working-capital cycle -- with DSO and DPO explicitly
labeled as stated assumptions (not derived figures), never fabricated
from data that doesn't exist. 12 new tests (27 total across both stages)
cover the cleaning decision log, the return/variable-cost model, and every
KPI formula.

**Stopping here for review before Stage 3** (the fashion industry module
via the config boundary) -- which will also be where the loss-maker
calibration gap gets fixed, since that's exactly where CAC becomes a
first-class, reusable KPI rather than diagnostic-only code."""
    ),
]


def build():
    nb = nbf.v4.new_notebook()
    nb["cells"] = STAGE_1_CELLS + STAGE_2_CELLS
    nb["metadata"] = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
        "colab": {"provenance": []},
    }
    with open(NB_PATH, "w") as f:
        nbf.write(nb, f)
    print(f"Wrote {NB_PATH} with {len(nb['cells'])} cells")


if __name__ == "__main__":
    build()
